import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Navbar from "../src/components/Navbar/Navbar";
import NavBottom from "../src/components/NavbarBottomContent";
import Card from "../src/components/Card";
import Footer from "../src/components/footer";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Example UI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className="top-container">
        <Navbar />
        <NavBottom />
      </nav>
      <main>
        <div className="card-container">
          <h1>Your BookMarks</h1>
          <div style={{ display: "flex" }}>
            <Card
              title={"Edit PDF"}
              description={"some Description here "}
              src={
                "https://i.pinimg.com/474x/52/29/3f/52293f2d5baaa98fba373d0c18ec002c.jpg"
              }
            />
            <Card
              title={"Crop pdf"}
              description={"some Description here "}
              src={
                "https://i.pinimg.com/474x/52/29/3f/52293f2d5baaa98fba373d0c18ec002c.jpg"
              }
            />
            <Card
              title={"Replace Text"}
              description={"some Description here "}
              src={
                "https://i.pinimg.com/474x/52/29/3f/52293f2d5baaa98fba373d0c18ec002c.jpg"
              }
            />
            <Card
              title={"Rotate Pdf"}
              description={"some Description here "}
              src={
                "https://i.pinimg.com/474x/52/29/3f/52293f2d5baaa98fba373d0c18ec002c.jpg"
              }
            />
          </div>
        </div>
        <div className="card-container1">
          <h1 style={{ marginLeft: "5rem" }}>Convert From PDF</h1>
          <button className="all-button">{"All >"}</button>
          <div style={{ display: "flex" }} className="content-container">
            <div className="arrow">
              <img
                width={"40rem"}
                src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAT4AAACfCAMAAABX0UX9AAAAZlBMVEX///8AAABWVlaysrLz8/Pn5+f19fXr6+uwsLArKysXFxetra0dHR0aGhohISHl5eUwMDAoKChvb28RERG9vb2AgIDHx8diYmJBQUF0dHTS0tJJSUlnZ2egoKB6enqIiIiRkZE3NzceRBweAAACy0lEQVR4nO3dbU8TURBA4b243cqLrUVoQXnR//8nJRDEtqNceoiTief5DplMDqXsXrbD8I4urhdtdfn1Pb/l/2P81p7cTNmjFDRrv5y4v7ean72sr51nT1PNvG1ZZs9Ty1Z7D26zByplp73W7rInqmS3Pdf3FnvttXafPVMds732WltnD1VG0F47zh6qjKi95t9tnaL22ofsqaqYfXJ7h7M9wvaI+Re3dzjbI2yPmJ24vcPZHmF7xNztATN/cgHbI2yPsD3C9gjbI2bB8txeL9sjbI+Ye4UKsD3C9gjbI7wyT9geYXuE7RG2R3gSg7A9wvYI2yNsj/BuOGF7hO0RtkfYHuEJNGLp9gDbI2yPsD3C9gjPUBHLYHlur5ftEbZH+JcaYXuE7RG2R9geYXuE7RGeAiJsj7A9ImzvInuqKsL2Fpsj/dnN9+fHsy6j9vSqpydkjtljlPX4lMKr7Cnq2gzDOnuGytbDefYIlV0P0elRdVoN2RPUZn3Ewtc+4tzfvMR6GDbZM9R19PC2efLV70BPz0Yfj7PnqOn5UyHGqL8zr7j8zd3tywfihP15va9b2J9Xm7uF/bm/bvbH2B9jf4z9MWF/H7OnqmOK+jvNnqqOMfrcJvfXzf6YceH+CPtj7I+xP2ZcuT9icn+I/TH2x9gfY39MeP3K/XWbfP+M2B9jf4z9MZPXTxH7Y+yPsT/G/pjxc7A/7/92C/tzf93sjwnvn7u/bpP9IfbHhPcv3V+38P65++vm6x9jf4z9MfbH2B8T3j93f918/8eE/fn/H93C/txfN///iLE/xv6Y8Pya++tmf4z9MfbH2B8T3r90f93C85Pur5v9MfbHhP35/KtuYX/z7KnqiK7f32cPVUjQ3yp7pkqC/rJHKmW/v+yJatnrL3ugYnb6u86ep5rt/pavf4G2/N7fZfYwBU1Xbg85fTzA+2OdPce/8xNi5S/3d849lwAAAABJRU5ErkJggg=="
                alt=""
              />
            </div>
            <Card
              title={"Edit PDF"}
              description={"some Description here "}
              src={"https://images.hipdf.com/images2022/icons/word-pdf.svg"}
            />
            <Card
              title={"Crop pdf"}
              description={"some Description here "}
              src={"https://images.hipdf.com/images2022/icons/PPT-PDF.svg"}
            />
            <Card
              title={"Replace Text"}
              description={"some Description here "}
              src={"https://images.hipdf.com/images2022/icons/Excel-PDF.svg"}
            />
            <Card
              title={"Rotate Pdf"}
              description={"some Description here "}
              src={"https://images.hipdf.com/images2022/icons/jpg-pdf.svg"}
            />
            <Card
              title={"Rotate Pdf"}
              description={"some Description here "}
              src={"https://images.hipdf.com/images2022/icons/Image-in-TXT.svg"}
            />
            <div className="arrow">
              <img
                width={"40rem"}
                src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAOEAAADhCAMAAAAJbSJIAAAAclBMVEX///8AAABubm5mZmbExMTS0tImJiapqan7+/s7Ozurq6vHx8fV1dWmpqbMzMw4ODgWFhYhISEzMzMQEBAtLS0ICAgoKCgcHBxRUVGcnJwYGBjx8fHf3998fHzm5uYuLi64uLiFhYVERERMTExBQUFbW1u+cLgDAAACsklEQVR4nO3d3XLaMBBAYalpYuqWQExJcPgJDs37v2IhTTtepjO98mh6dL5rLrQjW2tp1yYlSZIkSZIkSZIkSZIkSZIkSZIkou1uW3oIkzrsN6+b/aH0MKZze8oX3bfSA5nK4S1/uC09lIm0698RZugs9n8CzMv70oOZxCjC3H0tPZopNKMI85fPpYczgd1mHOKCOIvtahziI3FFjSEik8YoYVBDnD/gQ2wfxxF+By43sxgiMWnM2rsQInAW03wZLlTivTjnr6g1JI0nfoghL94Rl5smrKgLYtJowiwSk8Zs/jwOsSPu+udhtVkSz25qSBpxv0icxZg0npD3YkgaHTFpxFlEbqbiA9yCeKGOD4pzfkAuNxUkjRgicRb7cC+uiPdiXFGJZZsKkwZwFlMflhtk2aaGpJHxIfZLfIhxuUGWbapLGsQTuNSHg40X4gNc3EytiY/hNSQNfsdGH07DiWWb68dwYNJIf29nmB2HTxQ34Rj1o2yzO8Vnc5Tnc9LYrv79u//YepuG0mOY2JAWpYcwsS6xL9KcVxXM4VB6CBMb0rb0EKZ1XkvT7gc8H54zYru/oXiLrcTAVpRjNw4QeF6DbwnDt/XFdjDgHh/fKRULNMCzttjmzjsvxXedXr+LAUwTIUBg7Qnfwd9meIAN/TB/Dn+F9ipN8Ppp+GmiCXUKYF9b3C4BexNb+ksJ+Lf043aJ1+d9nSZw9yD/5fUYIPCdGfx7T01st8QtMrWdqgHfIW3Cjp5XfOF/ACSmCWDxJVaXiMUX/KkaPU3gT9Ua+DeG8Gmitu0SsfhC/+YePk3gT9WO4RLlFV/S7jQOkFd8uaqAAtNEDd+C5n/Pe3SV8s5k3vG/q5/uX3+lCegMXrz/v8UA/n+LdPmPklnpIUiSJEmSJEmSJEmSJEmSJEmSpEr8BBiHKfPcGeC7AAAAAElFTkSuQmCC"
                alt=""
              />
            </div>
          </div>
        </div>
        <div className="card-container2">
          <h1>Convert From PDF</h1>
          <div style={{ display: "flex" }} className="content-container">
            <Card
              title={"Edit PDF"}
              description={"some Description here "}
              src={"https://images.hipdf.com/images2022/icons/word-pdf.svg"}
            />
            <Card
              title={"Crop pdf"}
              description={"some Description here "}
              src={"https://images.hipdf.com/images2022/icons/PPT-PDF.svg"}
            />
            <Card
              title={"Replace Text"}
              description={"some Description here "}
              src={"https://images.hipdf.com/images2022/icons/Excel-PDF.svg"}
            />
            <Card
              title={"Rotate Pdf"}
              description={"some Description here "}
              src={"https://images.hipdf.com/images2022/icons/jpg-pdf.svg"}
            />
            <Card
              title={"Rotate Pdf"}
              description={"some Description here "}
              src={"https://images.hipdf.com/images2022/icons/Image-in-TXT.svg"}
            />
          </div>
        </div>
        <div className="card-container3">
          <h1>Convert From PDF</h1>
          <div style={{ display: "flex" }} className="content-container">
            <Card
              title={"Edit PDF"}
              description={"some Description here "}
              src={"https://images.hipdf.com/images2022/icons/word-pdf.svg"}
            />
            <Card
              title={"Crop pdf"}
              description={"some Description here "}
              src={"https://images.hipdf.com/images2022/icons/PPT-PDF.svg"}
            />
            <Card
              title={"Replace Text"}
              description={"some Description here "}
              src={"https://images.hipdf.com/images2022/icons/Excel-PDF.svg"}
            />
            <Card
              title={"Rotate Pdf"}
              description={"some Description here "}
              src={"https://images.hipdf.com/images2022/icons/jpg-pdf.svg"}
            />
            <Card
              title={"Rotate Pdf"}
              description={"some Description here "}
              src={"https://images.hipdf.com/images2022/icons/Image-in-TXT.svg"}
            />
          </div>
        </div>
      </main>
      <footer className="footer-main">
       <Footer/>
      </footer>
    </div>
  );
}
